calculate significant numbers
rl-institut/django-mapengine pull request #2
Opened 2023-04-17 08:48 UTC by Josephine-Marie

add functions for calculating the upper and lower value limit for each choropleth object.

2023-04-18 12:46 UTC, Josephine-Marie commented
Upper and lower value get generated from list of values. (from explicitly handing a list, not the "values" from choropleth.json)
amount of steps is now fixed to 6 (because of 6 legend entries) -> "num_colors" can get deleted from choropleth.json

@henhuy pls take a look and best case merge it

2023-04-21 08:55 UTC, henhuy requested changes
Thanks for implementing better min/max bounds!
one request: I would reset number of colors to dynamic amount as this could be useful if we want to show data with either less or even more colors.

2023-04-21 08:55 UTC, henhuy commented on django_mapengine/choropleth.py
> +            step = (max_value - min_value) / 5
Why did you remove dynamic number of colors and replaced it with fixed one?
Suggestion: Make 6 the default (as constant) but, allow more colors if needed (up to max of 9, as this is current limitation by colorbrewer)

2023-04-21 08:55 UTC, henhuy commented on django_mapengine/choropleth.py
> +        length = len(str(mini))
I think those str-to-int-to-str conversions could be rewritten to mathematical functions, but I would be okay with this.

2023-04-24 09:14 UTC, Josephine-Marie commented on django_mapengine/choropleth.py
> +        length = len(str(mini))
yes, it is way better now! :+1:

2023-04-26 08:33 UTC, merged